export {default as logo} from "./logo.svg"
export {default as netoyageFemme} from "./netoyage-femme.jpg"
export {default as netoyageGp} from "./netoyageGp.jpg"
export {default as Netoyage1} from "./netoyage-1.jpg"
export {default as Netoyage2} from "./netoyage-2.jpg"
export {default as Netoyage3} from "./netoyage-homme.jpg"
export {default as tenoinFemme} from "./temoin-femme.jpg"
export {default as logo1} from "./logo1.jpg"
export {default as logo2} from "./logo2.jpg"
export {default as logo3} from "./logo3.jpg"
export {default as tondeuse} from "./tondeuse.jpg"
export {default as femmeMenager} from "./femme-menager.jpg"
export {default as desinsectisation} from "./desinsectisation.jpg"
export {default as gestionDechet} from "./gestion-dechet.jpg"
export {default as curage} from "./curage.jpg"
export {default as bgNetoyage} from "./bg-header-netoyage.jpg"
export {default as managerFemme} from "./menager-femme2.jpg"
export {default as espaceVerts} from "./espace-verts-tondeuse.jpg"
export {default as tondeuse1} from "./tondeuse1.jpg"
export {default as desinsectisation1} from "./desinsectisation1.jpg"
export {default as bgDechet} from "./bg-header-dechet.jpg"
export {default as dechet} from "./dechet.jpg"
export {default as bgVidange} from "./vidange.jpg"
export {default as temoin1} from "./temoin1.jpg"
export {default as temoin2} from "./temoin2.jpg"
export {default as temoin3} from "./temoin3.jpg"
export {default as temoin4} from "./temoin4.jpg"
export {default as temoin5} from "./temoin5.jpg"
export {default as temoin6} from "./temoin6.jpg"
export {default as temoin7} from "./temoin7.jpg"




